export const users = [
  {
    id: 1,
    name: "John Doe",
    position: "Manager",
    email: "john.doe@example.com",
    lastLogIn: "2023-07-01T10:00:00Z",
    status: "active",
  },
  {
    id: 2,
    name: "Jane Smith",
    position: "Developer",
    email: "jane.smith@example.com",
    lastLogIn: "2023-07-02T11:00:00Z",
    status: "blocked",
  },
  {
    id: 3,
    name: "Bob Johnson",
    position: "Designer",
    email: "bob.johnson@example.com",
    lastLogIn: "2023-07-03T12:00:00Z",
    status: "active",
  },
  {
    id: 4,
    name: "Alice Brown",
    position: "QA Engineer",
    email: "alice.brown@example.com",
    lastLogIn: "2023-07-04T13:00:00Z",
    status: "blocked",
  },
  {
    id: 5,
    name: "Michael Davis",
    position: "Product Owner",
    email: "michael.davis@example.com",
    lastLogIn: "2023-07-05T14:00:00Z",
    status: "active",
  },
  {
    id: 6,
    name: "Emily Wilson",
    position: "Scrum Master",
    email: "emily.wilson@example.com",
    lastLogIn: "2023-07-06T15:00:00Z",
    status: "blocked",
  },
  {
    id: 7,
    name: "David Martinez",
    position: "Business Analyst",
    email: "david.martinez@example.com",
    lastLogIn: "2023-07-07T16:00:00Z",
    status: "active",
  },
  {
    id: 8,
    name: "Sophia Anderson",
    position: "HR Specialist",
    email: "sophia.anderson@example.com",
    lastLogIn: "2023-07-08T17:00:00Z",
    status: "blocked",
  },
  {
    id: 9,
    name: "James Thomas",
    position: "System Administrator",
    email: "james.thomas@example.com",
    lastLogIn: "2023-07-09T18:00:00Z",
    status: "active",
  },
  {
    id: 10,
    name: "Olivia Lee",
    position: "UX Researcher",
    email: "olivia.lee@example.com",
    lastLogIn: "2023-07-10T19:00:00Z",
    status: "blocked",
  },
  {
    id: 11,
    name: "Daniel Perez",
    position: "Marketing Manager",
    email: "daniel.perez@example.com",
    lastLogIn: "2023-07-11T20:00:00Z",
    status: "active",
  },
  {
    id: 12,
    name: "Mia Clark",
    position: "Content Writer",
    email: "mia.clark@example.com",
    lastLogIn: "2023-07-12T21:00:00Z",
    status: "blocked",
  },
  {
    id: 13,
    name: "Ethan Taylor",
    position: "Support Engineer",
    email: "ethan.taylor@example.com",
    lastLogIn: "2023-07-13T22:00:00Z",
    status: "active",
  },
  {
    id: 14,
    name: "Isabella Hall",
    position: "Sales Manager",
    email: "isabella.hall@example.com",
    lastLogIn: "2023-07-14T23:00:00Z",
    status: "blocked",
  },
  {
    id: 15,
    name: "Alexander Moore",
    position: "DevOps Engineer",
    email: "alexander.moore@example.com",
    lastLogIn: "2023-07-15T09:00:00Z",
    status: "active",
  },
  {
    id: 16,
    name: "Charlotte Lee",
    position: "Project Manager",
    email: "charlotte.lee@example.com",
    lastLogIn: "2023-07-16T08:00:00Z",
    status: "blocked",
  },
  {
    id: 17,
    name: "Benjamin Harris",
    position: "Data Scientist",
    email: "benjamin.harris@example.com",
    lastLogIn: "2023-07-17T07:00:00Z",
    status: "active",
  },
  {
    id: 18,
    name: "Amelia Robinson",
    position: "Security Specialist",
    email: "amelia.robinson@example.com",
    lastLogIn: "2023-07-18T06:00:00Z",
    status: "blocked",
  },
  {
    id: 19,
    name: "Lucas White",
    position: "Network Engineer",
    email: "lucas.white@example.com",
    lastLogIn: "2023-07-19T05:00:00Z",
    status: "active",
  },
  {
    id: 20,
    name: "Harper Martinez",
    position: "Graphic Designer",
    email: "harper.martinez@example.com",
    lastLogIn: "2023-07-20T04:00:00Z",
    status: "blocked",
  },
  {
    id: 21,
    name: "Mason Clark",
    position: "Accountant",
    email: "mason.clark@example.com",
    lastLogIn: "2023-07-21T03:00:00Z",
    status: "active",
  },
  {
    id: 22,
    name: "Ella Lewis",
    position: "Legal Advisor",
    email: "ella.lewis@example.com",
    lastLogIn: "2023-07-22T02:00:00Z",
    status: "blocked",
  },
  {
    id: 23,
    name: "Logan Walker",
    position: "Finance Manager",
    email: "logan.walker@example.com",
    lastLogIn: "2023-07-23T01:00:00Z",
    status: "active",
  },
  {
    id: 24,
    name: "Avery Allen",
    position: "Event Coordinator",
    email: "avery.allen@example.com",
    lastLogIn: "2023-07-24T23:00:00Z",
    status: "blocked",
  },
  {
    id: 25,
    name: "Aiden Young",
    position: "PR Specialist",
    email: "aiden.young@example.com",
    lastLogIn: "2023-07-25T22:00:00Z",
    status: "active",
  },
  {
    id: 26,
    name: "Evelyn King",
    position: "Community Manager",
    email: "evelyn.king@example.com",
    lastLogIn: "2023-07-26T21:00:00Z",
    status: "blocked",
  },
  {
    id: 27,
    name: "Carter Scott",
    position: "Customer Success Manager",
    email: "carter.scott@example.com",
    lastLogIn: "2023-07-27T20:00:00Z",
    status: "active",
  },
  {
    id: 28,
    name: "Grace Green",
    position: "Administrative Assistant",
    email: "grace.green@example.com",
    lastLogIn: "2023-07-28T19:00:00Z",
    status: "blocked",
  },
  {
    id: 29,
    name: "Sebastian Adams",
    position: "Operations Manager",
    email: "sebastian.adams@example.com",
    lastLogIn: "2023-07-29T18:00:00Z",
    status: "active",
  },
  {
    id: 30,
    name: "Chloe Baker",
    position: "Office Manager",
    email: "chloe.baker@example.com",
    lastLogIn: "2023-07-30T17:00:00Z",
    status: "blocked",
  },
  {
    id: 31,
    name: "Jack Hill",
    position: "Recruitment Specialist",
    email: "jack.hill@example.com",
    lastLogIn: "2023-07-31T16:00:00Z",
    status: "active",
  },
  {
    id: 32,
    name: "Victoria Mitchell",
    position: "Executive Assistant",
    email: "victoria.mitchell@example.com",
    lastLogIn: "2023-08-01T15:00:00Z",
    status: "blocked",
  },
  {
    id: 33,
    name: "Henry Perez",
    position: "IT Support",
    email: "henry.perez@example.com",
    lastLogIn: "2023-08-02T14:00:00Z",
    status: "active",
  },
  {
    id: 34,
    name: "Aria Roberts",
    position: "Product Designer",
    email: "aria.roberts@example.com",
    lastLogIn: "2023-08-03T13:00:00Z",
    status: "blocked",
  },
  {
    id: 35,
    name: "Matthew Parker",
    position: "Technical Writer",
    email: "matthew.parker@example.com",
    lastLogIn: "2023-08-04T12:00:00Z",
    status: "active",
  },
  {
    id: 36,
    name: "Scarlett Phillips",
    position: "SEO Specialist",
    email: "scarlett.phillips@example.com",
    lastLogIn: "2023-08-05T11:00:00Z",
    status: "blocked",
  },
  {
    id: 37,
    name: "Leo Evans",
    position: "Mobile Developer",
    email: "leo.evans@example.com",
    lastLogIn: "2023-08-06T10",
    status: "blocked",
  },
];
